//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to secure a REST service with the Open Liberty SocialLogin feature.
:guide-author: Open Liberty
:page-tags: ['Social Login', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:page-seo-title: Securing a REST service with Social Login
:page-seo-description: A tutorial on how to secure a REST service in Open Liberty using the SocialLogin feature
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Securing a RESTful web service with Social Login

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to secure a REST service with the Open Liberty SocialLogin feature.

== What you'll learn

You will learn how to secure and test a simple REST service with SocialLogin. You will secure an existing service,
`HelloService` using social media OAuth2 and OpenID Connect.
You will secure your `Hello` service with three social media login choices:

1. Github login
2. Amazon login
3. Google login

`HelloService` is an existing microservice that responds to a `GET` request with a Plain Text response that looks like this:

[source,role="no_copy"]
----
Hello, friend!
----

In order to secure this endpoint, you will use the Open Liberty `SocialLogin` feature.
This feature allows you to easily secure your service

=== Prerequisites

Before you can run/build the application, you will need to add the social media domains' certificates to the truststore for social login.
The application we will build in this guide requires certificates for Amazon, Google and Github to be added to the truststore.
You also need to create certificates that your application will provide for HTTPS connections. This certificate and private key will need to be added to the keystore for social login.
Lastly, you need to create applications on the three social media developer platforms to obtain a client ID and client secret to use their APIs.

To get the certificates for Amazon, Google and Github,

1. Open the website on Firefox.
2. Click on the button next to "Connection Secure".
3. Click on "More Information".
4. Click on "View Certificate".
5. Download each certificate in the chain as a separate `PEM` file.

Once you have the certificates downloaded, you need to add them to the trust store.
As part of the guide, you will be configuring the application's trust store to be `slts.p12` whose password is `changeit`.
Run the following command to add a certificate to the trust store. The command also creates the trust store file if it doesn't exist.
[role='command']
```
keytool -import -trustcacerts -file <certificate-file-name> -alias <certificate-alias> -keystore slts.p12 -storetype PKCS12 -storepass changeit
```

To generate certificates for your service to use for HTTPS connections, run the following command:
[role='command']
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```

Before the certificate and private key can be imported into the key store for your service, it needs to be converted into one `PKCS12` bundle.
Combine your key and certificate by running the following command:
[role='command']
```
openssl pkcs12 -inkey key.pem -in cert.pem -export -out certificate.p12
```

The key store to be used by social login will be configured to be `key.p12` whose password is `changeit`.
To import your certificate bundle into this keystore, run the following command:
[role='command']
```
keytool -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore key.p12 -deststoretype PKCS12
```

To use the new key store and trust store, copy these files into `src/main/liberty/resources/security`
in the `start` and `finish` directories.

The last prerequisite step is obtaining client ID and client secret for access to the three social media developer APIs.

In order to obtain OAuth 2.0 credentials for Google, visit the https://console.developers.google.com/[Google API Console].

In order to obtain OAuth 2.0 credentials for Amazon, follow the steps here: https://auth0.com/docs/connections/social/amazon.

In order to obtain OAuth 2.0 credentials for Github, follow the steps here: https://auth0.com/docs/connections/social/github.

In order to try what you'll build, enter the client IDs and client secrets to the `server.xml` in the finish folder.

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the application, first go to the `finish` directory and run the following Maven 
goal to build the application and deploy it to Open Liberty:
[role='command']
```
mvn liberty:run
```

Check out the service at the
http://localhost:9080/api/hello[^] URL.

After you are done checking out the application, stop the Open Liberty server by pressing `CTRL+C`
in the shell session where you ran the server. Alternatively, you can run the `liberty:stop` goal 
from the `finish` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

== Securing the JAX-RS service

Navigate to the `start` directory to begin.

Start Open Liberty in development mode, which starts the Open Liberty server and listens 
for file changes:

[role="command"]
```
mvn liberty:dev
```

The `socialLogin` feature provides the following social login configurations:

1. `facebookLogin`
2. `githubLogin`
3. `googleLogin`
4. `linkedinLogin`

The feature also provides the `oauth2Login` and `oidcLogin` configuration elements for creating custom social media login configurations.
In this guide, you will secure your `Hello` service with three social media login choices:

1. Github login using `githubLogin`
2. Amazon login using a custom `oauth2Login`
3. Google login using a custom `oidcLogin`

=== Securing Hello Service

[role="code_command hotspot" ,subs="quotes"]
----
#Update the `HelloService` class.#
`src/main/java/io/openliberty/guides/sociallogin/HelloService.java`
----

The [hotspot=helloService]`HelloService` class is the JAX-RS service that you will be securing.
Add the [hotspot=rolesAllowed]`@RolesAllowed({"users"})` annotation to restrict access to the service to users who are
in the `Users` role.

HelloService.java
[source, Java, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloService.java[]
----

Next, you will replace the `return "Hello, friend!";` to output user information instead of `friend`.

First, add the [hotspot=httpServletRequestContext]`HttpServletRequest` context.
Next, use [hotspot=userPrincipal]`request.getUserPrincipal()` to get information about the logged in user.

=== Configuring the security roles

[role="code_command hotspot", subs="quotes"]
----
#Update the `server.xml` file.#
`src/main/liberty/config/server.xml`
----

Server.xml
[source, xml, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/liberty/config/server.xml[]
----

Modify the [hotspot=webApplication]`webApplication` tag in `server.xml` to create the security role `users` by adding
the [hotspot=applicationBnd]`application-bnd` element:

The [hotspot=applicationBnd]`application-bnd` configuration element creates a new security role `users`, which all authenticated users belong to. Adding this allows
users that are authenticated using social media login to access your `HelloService` service.

=== Configuring the server to add social media login

[role="code_command hotspot", subs="quotes"]
----
#Update the `server.xml` file.#
`start/src/main/liberty/config/server.xml`
----

Server.xml
[source, xml, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/liberty/config/server.xml[]
----

Add the following OpenLiberty [hotspot=features]`feature elements` to `server.xml`:

[role="command"]
----
<feature>appSecurity-3.0</feature>
<feature>transportSecurity-1.0</feature>
<feature>socialLogin-1.0</feature>
<feature>ssl-1.0</feature>
<feature>jwt-1.0</feature>
----

These features enable SocialLogin and other related features.

Before you add social media login configuration elements, there are some prerequisite configurations that need to be made:

1. Create a `keyStore` configuration element that corresponds to the key store created in the prerequisites section
2. Create a `keyStore` configuration element that corresponds to the trust store created in the prerequisites section
3. Create an `ssl` configuration element for configuring the SSL configuration that is used to connect to the social media

=== Configuring SSL for social media login

[role="code_command hotspot", subs="quotes"]
----
#Update the `server.xml` file.#
`start/src/main/liberty/config/server.xml`
----

Server.xml
[source, xml, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/liberty/config/server.xml[]
----

In the prerequisites section, you created two key stores, `slts.p12` and `key.p12`. Now you will configure your application
to use these key stores. Files in the `src/liberty` folder are copied into the location specified by `${server.output.dir}`,
so the location of these key stores is `${server.output.dir}/resources/security`.

Create a [hotspot=keystore]`keyStore` configuration element whose location is `${server.output.dir}/resources/security/key.p12`.
Provide the password that you used when creating the key store. This `defaultKeyStore` will be used to provide SSL certificates when initiating HTTPS connections for social media login.

Next, create a [hotspot=truststore]`keyStore` configuration element whose locaiton is `${server.output.dir}/resources/security/slts.p12`.
Provide the password that you usd when creating the trust store. This `socialLoginKeyStore` will be usd to store trusted certificates when initiating HTTPS connections to social media APIs for authorization and authentication.

Finally, create a [hotspot=sslConfig]`ssl` configuration element which references `defaultKeyStore` as the key store and `socialLoginKeyStore` as the trust store.
This SSL configuration will be provided to social media login configurations.

== Configuring the server

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The configuration does the following actions:

. Configures the server to enable JAX-RS. This is specified in the [hotspot=featureManager file=0]`featureManager` element.
. Configures the server to resolve the HTTP port numbers from variables, which are then specified in
the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort file=1]`pom.xml` file. This is specified in the [hotspot=httpEndpoint file=0]`<httpEndpoint/>` element. Variables use the `${variableName}` syntax.
. Configures the server to run the produced web application on a context root specified in the 
[hotspot=appContextRoot file=1]`pom.xml` file. This is specified in the [hotspot=webApplication file=0]`<webApplication/>` element.

pom.xml
[source,xml,linenums,role="code_column"]
----
include::finish/pom.xml[]
----

The variables that are being used in the [hotspot=httpEndpoint hotspot=webApplication file=0]`server.xml` file are provided by the properties set in the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort hotspot=appContextRoot file=1]`pom.xml` file. The properties must be formatted as `liberty.var.variableName`.

== Building and running the application

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

Check out the service that you created at the
http://localhost:9080/LibertyProject/System/properties[^] URL. 


== Testing the service

You can test this service manually by starting a server and pointing a web browser at the
http://localhost:9080/LibertyProject/System/properties[^] URL. Automated tests are a much better
approach because they trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

[role="code_command hotspot", subs="quotes"]
----
#Create the `EndpointIT` class.#
`src/test/java/it/io/openliberty/guides/rest/EndpointIT.java`
----

EndpointIT.java
[source, Java, linenums, role="code_column hide_tags=comment"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointIT.java[]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the [hotspot=test file=0]`@Test` annotation.

pom.xml
[source , xml, linenums,role="code_column"]
----
include::finish/pom.xml[]
----

The test code needs to know some information about the application to make requests. The server port and the application context root are key, and are dictated by the server configuration. While this information can be hardcoded, it is better to specify it in a single place like the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort hotspot=appContextRoot file=1]`pom.xml` file. Refer to the [hotspot file=1]`pom.xml` file to see how the application information such as the [hotspot=defaultHttpPort file=1]`default.http.port`, [hotspot=defaultHttpsPort file=1]`default.https.port` and [hotspot=appContextRoot file=1]`app.context.root` elements are provided in the file.


These Maven properties are then passed to the Java test program as the [hotspot=testsysprops file=1]`<systemPropertyVariables/>` element in the [hotspot file=1]`pom.xml` file.

Getting the values to create a representation of the URL is simple. The test class uses the [hotspot=systemProperties file=0]`getProperty` method
to get the application details.

To call the JAX-RS service using the JAX-RS client, first create a `WebTarget` object by calling
the [hotspot=target file=0]`target` method that provides the URL. To cause the HTTP request to occur, the [hotspot=requestget file=0]`request().get()` method
is called on the `WebTarget` object. The [hotspot=requestget file=0]`get` method
call is a synchronous call that blocks until a response is received. This call returns a [hotspot=requestget file=0]`Response`
object, which can be inspected to determine whether the request was successful.

The first thing to check is that a `200` response was received. The JUnit [hotspot=assertequals file=0]`assertEquals` method can be used for this check.

Check the response body to ensure it returned the right information. Since the client and the server
are running on the same machine, it is reasonable to expect that the system properties for the local
and remote JVM would be the same. In this case, an [hotspot=assertosname file=0]`assertEquals` assertion is made so that the `os.name` system property
for both JVMs is the same. You can write additional assertions to check for more values.

=== Running the tests

Since you started Open Liberty in development mode at the start of the guide, press
`enter/return` key to run the tests. You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointIT

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

When you are done checking out the service, exit development mode by typing `q` in the shell session where
you ran the server and then pressing the `enter/return` key.


== Great work! You're done!

You developed a REST service in Open Liberty by using JAX-RS and JSON-B.

== Related Links

Earn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
